#######################################
# Global Configuration
#######################################

mesh_path: "model://nubots_nugus_hull/mesh/"
mat_path: "file://media/materials/scripts/gazebo.material"

# Configuration for all joints between links
joint:
  dynamics:
    friction: 0.5
    damping: 0.6
    spring_reference: 0
    spring_stiffness: 3.25
  # Servo-specific config
  mx64:
    limit:
      effort: 7.3         # stall torque (Nm)
      velocity: 8.16814   # max. radial velocity (rad/s)
  mx106:
    limit:
      effort: 10.0        # stall torque (Nm)
      velocity: 5.75959   # max. radial velocity (rad/s)

# Configuration for all links
link:
  friction:
    mu: 0.98
    mu2: 0.98
    slip1: 0.001
    slip2: 0.001
    torsional: # http://gazebosim.org/tutorials?tut=torsional_friction&cat=physics
      coefficient: 0.8
      patch_radius: 1.0

#######################################
# IMU Sensor
#######################################

# Configuration for IMU sensor
sensor:
  update_rate: 100 # (Hz)
  pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
  gyro_noise:
    mean: [0.0, 0.0, 0.0]   # xyz (rad/s)
    stddev: [0.0, 0.0, 0.0] # xyz (rad/s)
  accel_noise:
    mean: [0.0, 0.0, 0.0]   # xyz (m/s^2)
    stddev: [0.0, 0.0, 0.0] # xyz (m/s^2)

#######################################
# Links
#######################################

# Configuration for all links of the NUgus
links:
  # Torso
  - torso:
      sensor: True
      link_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 1.570796327]                      # xyz rpy (m,rad)
      inertial_pose: [0.0, 0.000339, 0.112557, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]         # xyz rpy (m,rad)
      mass: 1.9581 # (kg)
      inertia: # (Nm)
      - [0.0316879323, 0, 0]
      - [0, 0.0366712968, -0.00022557312]
      - [0, -0.00022557312, 0.01878092034]
      mesh: "torso.stl"
      colour: "Gazebo/Grey"

  # Right shoulder pitch
  - right_shoulder:
      link_pose: [0.005, -0.115, 0.18, -1.570796327, 0, 1.570796327]    # xyz rpy (m,rad)
      inertial_pose: [0.003491, -0.001684, 0.003753, 0.0, 0.0, 0.0]        # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.060 # (kg)
      inertia: # (Nm)
      - [7.632e-06, 2.4e-08, -4.2e-07]
      - [2.4e-08, 5.82e-06, 7.2e-08]
      - [-4.2e-07, 7.2e-08, 7.536e-06]
      mesh: "right_shoulder.stl"
      colour: "Gazebo/Grey"
  # Left shoulder pitch
  - left_shoulder:
      link_pose: [0.005, 0.115, 0.18, -1.570796327, 0, 1.570796327]    # xyz rpy (m,rad)
      inertial_pose: [-0.003491, -0.001684, 0.003753, 0.0, 0.0, 0.0]        # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.060 # (kg)
      inertia: # (Nm)
      - [7.632e-06, -2.4e-08, 4.2e-07]
      - [-2.4e-08, 5.82e-06, 7.2e-08]
      - [4.2e-07, 7.2e-08, 7.536e-06]
      mesh: "left_shoulder.stl"
      colour: "Gazebo/Grey"

  # Right upper arm
  - right_upper_arm:
      link_pose: [0, -0.13, 0.18, 3.141590, 3.141590, -1.570796327]    # xyz rpy (m,rad)
      inertial_pose: [0.006723, -0.090631, 0.000549, 0.0, 0.0, 0.0]        # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.297 # (kg)
      inertia: # (Nm)
      - [8.835156e-05, 3.99762e-06,  -9.504e-08]
      - [3.99762e-06 , 1.483812e-05, 2.08494e-06]
      - [-9.504e-08  , 2.08494e-06,  9.10305e-05]
      mesh: "right_upper_arm.stl"
      colour: "Gazebo/Grey"
  # Left upper arm
  - left_upper_arm:
      link_pose: [0, 0.13, 0.18, 3.141590, 3.141590, -1.570796327]    # xyz rpy (m,rad)
      inertial_pose: [-0.006723, -0.090631, 0.000549, 0.0, 0.0, 0.0]        # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.297 # (kg)
      inertia: # (Nm)
      - [8.835156e-05, -3.99762e-06,  9.504e-08]
      - [-3.99762e-06 , 1.483812e-05, 2.08494e-06]
      - [9.504e-08  ,   2.08494e-06,  9.10305e-05]
      mesh: "left_upper_arm.stl"
      colour: "Gazebo/Grey"

  # Right lower arm
  - right_lower_arm:
      link_pose: [0.19, -0.12, 0.22, 0, 0, 1.570796327]   # xyz rpy (m,rad)
      inertial_pose: [0.004014, -0.060888, -0.000161, 0.0, 0.0, 0.0]        # xyz rpy (m,rad)
      display_pose: [0,0,0,0,0,0] # xyz rpy (m,rad)
      mass: 0.26 # (kg)
      inertia: # (Nm)
      - [0.0011613, -5.8221e-07, -7.4224e-05]
      - [0.0, 0.0011747, 2.0082e-05]
      - [0.0, 0.0, 0.00010273]
      mesh: "right_lower_arm.stl"
      colour: "Gazebo/Grey"
  # Left lower arm
  - left_lower_arm:
      link_pose: [0.19, 0.12, 0.22, 0, 0, 1.570796327]    # xyz rpy (m,rad)
      inertial_pose: [-0.004014, -0.060888, -0.000161, 0.0, 0.0, 0.0]        # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.26 # (kg)
      inertia: # (Nm)
      - [0.00081539, 1.1134e-07, -5.114e-05]
      - [0.0, 0.0007994, -2.4756e-06]
      - [0.0, 0.0, 0.00012883]
      mesh: "left_lower_arm.stl"
      colour: "Gazebo/Grey"

  # Right hip_yaw
  - right_hip_yaw:
      link_pose: [0, -0.055, 0, 0, 0, 1.570796327]   # xyz rpy (m,rad)
      inertial_pose: [0.001672, 0.008885, -0.026767, 0.0, 0.0, 0.0]        # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.22 # (kg)
      inertia: # (Nm)
      - [2.6774e-05, 1.5536e-19, -9.0622e-19]
      - [0.0, 0.00011478, -2.2736e-19]
      - [0.0, 0.0, 0.00010743]
      mesh: "right_hip_yaw.stl"
      colour: "Gazebo/Grey"
  # Left hip_yaw
  - left_hip_yaw:
      link_pose: [0, 0.055, 0, 0, 0, 1.570796327]    # xyz rpy (m,rad)
      inertial_pose: [-0.001672, 0.008885, -0.026767, 0.0, 0.0, 0.0]        # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.22 # (kg)
      inertia: # (Nm)
      - [2.6774e-05, 1.9727e-19, -8.7961e-19]
      - [0.0, 0.00011478, -2.3128e-19]
      - [0.0, 0.0, 0.00010743]
      mesh: "left_hip_yaw.stl"
      colour: "Gazebo/Grey"

  # Right hip_roll
  - right_hip_roll:
      link_pose: [0, -0.055, -0.06, 0, 0, 1.570796327]   # xyz rpy (m,rad)
      inertial_pose: [-0.000017, -0.000295, -0.004740, 0.0, 0.0, 0.0]        # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.306 # (kg)
      inertia: # (Nm)
      - [0.00015503, 1.738e-06, 8.5148e-06]
      - [0.0, 0.0003299, 2.4403e-07]
      - [0.0, 0.0, 0.0002782]
      mesh: "right_hip_roll.stl"
      colour: "Gazebo/Grey"
  # Left hip_roll
  - left_hip_roll:
      link_pose: [0, 0.055, -0.06, 0, 0, 1.570796327]   # xyz rpy (m,rad)
      inertial_pose: [0.000017, -0.000295, -0.004740, 0.0, 0.0, 0.0]        # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.306 # (kg)
      inertia: # (Nm)
      - [0.00015501, -1.7299e-06, 8.5156e-06]
      - [0.0, 0.00032958, -2.4435e-07]
      - [0.0, 0.0, 0.00027786]
      mesh: "left_hip_roll.stl"
      colour: "Gazebo/Grey"

  # Right thigh
  - right_upper_leg:
      link_pose: [0.01, -0.055, -0.05, -0.05, 0, 1.570796327] # xyz rpy (m,rad)
      inertial_pose: [0.000592, -0.005444, -0.102193, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      display_pose: [0, 0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.387 # (kg)
      inertia: # (Nm)
      - [0.0020951, 1.8755e-07, -0.00017816]
      - [0.0, 0.0020043, -5.4867e-06]
      - [0.0, 0.0, 0.00027919]
      mesh: "right_upper_leg.stl"
      colour: "Gazebo/Grey"
  # Left thigh
  - left_upper_leg:
      link_pose: [0.01, 0.055, -0.05, -0.05, 0, 1.570796327] # xyz rpy (m,rad)
      inertial_pose: [-0.000592, -0.005444, -0.102193, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      display_pose: [0, 0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.387 # (kg)
      inertia: # (Nm)
      - [0.0020952, -1.9541e-07, -0.00017822]
      - [0.0, 0.0020044, 5.4912e-06]
      - [0.0, 0.0, 0.00027919]
      mesh: "left_upper_leg.stl"
      colour: "Gazebo/Grey"

  # Right lower leg
  - right_lower_leg:
      link_pose: [0.01, -0.055, -0.25, 0, 0, 1.570796327] # xyz rpy (m,rad)
      inertial_pose: [-0.002452, 0.006376, -0.088280, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      display_pose: [0, 0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.177 # (kg)
      inertia: # (Nm)
      - [0.0011378, -2.8771e-12, 9.7123e-05]
      - [0.0, 0.0010393, -1.4479e-11]
      - [0.0, 0.0, 0.00019656]
      mesh: "right_lower_leg.stl"
      colour: "Gazebo/Grey"
  # Left lower leg
  - left_lower_leg:
      link_pose: [0.01, 0.055, -0.25, 0, 0, 1.570796327] # xyz rpy (m,rad)
      inertial_pose: [0.002452, 0.006376, -0.088280, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      display_pose: [0, 0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.177 # (kg)
      inertia: # (Nm)
      - [0.0011378, -2.8771e-12, 9.7123e-05]
      - [0.0, 0.0010393, -1.4479e-11]
      - [0.0, 0.0, 0.00019656]
      mesh: "left_lower_leg.stl"
      colour: "Gazebo/Grey"

  # Right ankle
  - right_ankle:
      link_pose: [0, -0.055, -0.45, 0, 3.141590, 1.570796327] # xyz rpy (m,rad)
      inertial_pose: [0.000043, 0.021903, -0.010508, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.306 # (kg)
      inertia: # (Nm)
      - [0.00015501, 1.7299e-06, -8.5156e-06]
      - [0.0, 0.00032958, -2.4435e-07]
      - [0.0, 0.0, 0.00027786]
      mesh: "right_ankle.stl"
      colour: "Gazebo/Grey"
  # Left ankle
  - left_ankle:
      link_pose: [0, 0.055, -0.45, 0, 3.141590, 1.570796327] # xyz rpy (m,rad)
      inertial_pose: [-0.000043, 0.021903, -0.010508, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.306 # (kg)
      inertia: # (Nm)
      - [0.00015503, -1.738e-06, -8.5148e-06]
      - [0.0, 0.0003299, 2.4403e-07]
      - [0.0, 0.0, 0.0002782]
      mesh: "left_ankle.stl"
      colour: "Gazebo/Grey"

  # Right foot
  - right_foot:
      link_pose: [-0.04, -0.055, -0.45, 0, 0.0, 1.570796327] # xyz rpy (m,rad)
      inertial_pose: [-0.007551, -0.077046, -0.031619, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.205 # (kg)
      inertia: # (Nm)
      - [0.00018527, -1.1504e-05, -7.2667e-06]
      - [0.0, 0.00060485, 5.8883e-06]
      - [0.0, 0.0, 0.00075217]
      mesh: "right_foot.stl"
      colour: "Gazebo/Grey"
  # Left foot
  - left_foot:
      link_pose: [-0.04, 0.055, -0.45, 0, 0, 1.570796327] # xyz rpy (m,rad)
      inertial_pose: [0.007551, -0.077046, -0.031619, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.205 # (kg)
      inertia: # (Nm)
      - [0.0001853, 1.1466e-05, -8.3793e-06]
      - [0.0, 0.00060485, -5.9046e-06]
      - [0.0, 0.0, 0.00075213]
      mesh: "left_foot.stl"
      colour: "Gazebo/Grey"

  # Neck
  - neck:
      link_pose: [0, 0, 0.26, 0, 0, 1.570796327] # xyz rpy (m,rad)
      inertial_pose: [-0.000608, -0.000007, -0.015358, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.153 # (kg)
      inertia: # (Nm)
      - [4.2534e-06, 0.0000000, 1.224e-07]
      - [0.00000000, 4.437e-06, 0.0000000]
      - [1.224e-07, 0.0000000, 2.907e-06]
      mesh: "neck.stl"
      colour: "Gazebo/Grey"

  # Head
  - head:
      link_pose: [0, 0, 0.26, 0, 0, 1.570796327] # xyz rpy (m,rad)
      inertial_pose: [-0.002841, -0.003496, 0.064412, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      display_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # xyz rpy (m,rad)
      mass: 0.419 # (kg)
      inertia: # (Nm)
      - [0.0012, 0.0000, 0.0000]
      - [0.0000, 0.0013, 0.0000]
      - [0.0000, 0.0000, 0.0012]
      mesh: "head.stl"
      colour: "Gazebo/Grey"

#######################################
# Joints
#######################################

joints:
  # Shoulder pitch (0, 1)
  - right_shoulder_pitch:
      parent: "torso"
      child: "right_shoulder"
      axis: [0, 1, 0]
      type: "mx64"
  - left_shoulder_pitch:
      parent: "torso"
      child: "left_shoulder"
      axis: [0, 1, 0]
      type: "mx64"
  # Shoulder roll (2, 3)
  - right_shoulder_roll:
      parent: "right_shoulder"
      child: "right_upper_arm"
      axis: [0, 0, 1]
      type: "mx64"
  - left_shoulder_roll:
      parent: "left_shoulder"
      child: "left_upper_arm"
      axis: [0, 0, 1]
      type: "mx64"
  # Elbow (4, 5)
  - right_elbow_pitch:
      parent: "right_upper_arm"
      child: "right_lower_arm"
      axis: [0, 1, 0]
      type: "mx64"
  - left_elbow_pitch:
      parent: "left_upper_arm"
      child: "left_lower_arm"
      axis: [0, 1, 0]
      type: "mx64"
  # Hip yaw (6, 7)
  - right_hip_yaw:
      parent: "torso"
      child: "right_hip_yaw"
      axis: [0, 0, 1]
      type: "mx106"
  - left_hip_yaw:
      parent: "torso"
      child: "left_hip_yaw"
      axis: [0, 0, 1]
      type: "mx106"
  # Hip roll (8, 9)
  - right_hip_roll:
      parent: "right_hip_yaw"
      child: "right_hip_roll"
      axis: [1, 0, 0]
      type: "mx106"
  - left_hip_roll:
      parent: "left_hip_yaw"
      child: "left_hip_roll"
      axis: [1, 0, 0]
      type: "mx106"
  # Hip pitch (10, 11)
  - right_hip_pitch:
      parent: "right_hip_roll"
      child: "right_upper_leg"
      axis: [0, 1, 0]
      type: "mx106"
  - left_hip_pitch:
      parent: "left_hip_roll"
      child: "left_upper_leg"
      axis: [0, 1, 0]
      type: "mx106"
  # Knee (12, 13)
  - right_knee_pitch:
      parent: "right_upper_leg"
      child: "right_lower_leg"
      axis: [0, 1, 0]
      type: "mx106"
  - left_knee_pitch:
      parent: "left_upper_leg"
      child: "left_lower_leg"
      axis: [0, 1, 0]
      type: "mx106"
  # Ankle pitch (14, 15)
  - right_ankle_pitch:
      parent: "right_lower_leg"
      child: "right_ankle"
      axis: [0, 1, 0]
      type: "mx106"
  - left_ankle_pitch:
      parent: "left_lower_leg"
      child: "left_ankle"
      axis: [0, 1, 0]
      type: "mx106"
  # Ankle roll (16, 17)
  - right_ankle_roll:
      parent: "right_ankle"
      child: "right_foot"
      axis: [1, 0, 0]
      type: "mx106"
  - left_ankle_roll:
      parent: "left_ankle"
      child: "left_foot"
      axis: [1, 0, 0]
      type: "mx106"
  # Head yaw (18)
  - neck_yaw:
      parent: "torso"
      child: "neck"
      axis: [0, 0, 1]
      type: "mx64"
  # Head pitch (19)
  - head_pitch:
      parent: "neck"
      child: "head"
      axis: [0, 1, 0]
      type: "mx64"
